import React, { createContext, useContext, useMemo, useState } from 'react';

export type Language = 'en' | 'th';

type TranslationMap = Record<string, string>;

const enTranslations = {
  // Navigation & labels
  dashboard: 'Dashboard',
  personnel: 'Personnel',
  inventory: 'Inventory',
  requisitions: 'Requisitions',
  users_roles: 'Users & Roles',
  settings: 'Settings',
  storage_usage: 'Storage Usage',
  new_requisition: 'New Requisition',
  logout: 'Logout',
  search_placeholder: 'Search...',
  admin_portal: 'Admin Portal',
  admin_user: 'Admin User',
  language: 'Language',
  eng: 'Eng',
  thai: 'Thai',
  home: 'Home',
  users: 'Users',
  workplaces: 'Workplaces',
  create: 'Create',
  edit: 'Edit',
  view: 'View',
  slip: 'Slip',
  material_types: 'Material Types',
  workplace: 'Workplace',
  system: 'System',
  user: 'User',

  // Roles, access, status
  role_admin: 'Admin',
  role_user: 'User',
  role_personnel: 'Personnel',
  role_unknown: 'Unknown',
  access_full: 'Full Access',
  access_standard: 'Standard Access',
  access_na: 'N/A',
  status_active: 'Active',
  status_inactive: 'Inactive',
  status_suspended: 'Suspended',
  status_unknown: 'Unknown',
  status_approved: 'Approved',
  status_pending: 'Pending',
  status_rejected: 'Rejected',
  stock_in: 'In Stock',
  stock_low: 'Low Stock',
  stock_out: 'Out of Stock',

  // Common
  common_actions: 'Actions',
  common_all: 'All',
  common_all_status: 'All Status',
  common_apply_filters: 'Apply Filters',
  common_assigned: 'Assigned',
  common_cancel: 'Cancel',
  common_choose_file: 'Choose File',
  common_clear: 'Clear',
  common_close: 'Close',
  common_confirm_delete: 'Confirm Delete',
  common_date_created: 'Date Created',
  common_delete: 'Delete',
  common_deleting: 'Deleting...',
  common_edit: 'Edit',
  common_error: 'Error',
  common_error_required_fields: 'Please complete all required fields.',
  common_filters: 'Filters',
  common_from_date: 'From Date',
  common_items: 'items',
  common_last_updated: 'Last Updated',
  common_next: 'Next',
  common_no_changes: 'No changes made',
  common_of: 'of',
  common_optional: 'optional',
  common_previous: 'Previous',
  common_remove: 'Remove',
  common_required_hint: 'Required fields',
  common_reset: 'Reset',
  common_results: 'results',
  common_save_changes: 'Save Changes',
  common_saving: 'Saving...',
  common_showing: 'Showing',
  common_status: 'Status',
  common_to: 'to',
  common_to_date: 'To Date',
  common_unassigned: 'Unassigned',
  common_updated: 'Updated',
  common_updating: 'Updating...',
  common_view_all: 'View All',

  // Fallbacks
  no_email: 'No email',
  no_workplace: 'No workplace',
  not_available: 'N/A',
  not_set: 'Not set',

  // Labels & placeholders
  label_display_name: 'Display name',
  label_email_address: 'Email Address',
  label_full_name: 'Full Name',
  label_password: 'Password',
  label_position: 'Position',
  label_position_title: 'Job Position',
  label_role: 'Role',
  label_username: 'Username',
  placeholder_display_name_example: 'e.g. John Doe',
  placeholder_email_example: 'e.g. name@company.com',
  placeholder_fullname_example: 'e.g. John Doe',
  placeholder_position_example: 'e.g. Warehouse Manager',
  placeholder_username_example: 'e.g. jdoe',

  // Date picker
  datepicker_no_date_selected: 'No date selected',
  datepicker_invalid_date: 'Invalid date',
  datepicker_today: 'Today',

  // Login
  login_hero_title: 'Internal Management',
  login_hero_highlight: 'System',
  login_hero_subtitle: 'Manage requisitions, inventory, and personnel in one place.',
  login_title: 'Sign in',
  login_subtitle: 'Enter your credentials to continue.',
  login_email_placeholder: 'Email address',
  login_password_placeholder: 'Password',
  login_forgot_password: 'Forgot password?',
  login_sign_in: 'Sign In',
  login_logging_in: 'Logging in...',
  login_footer: '© Internal Management System',

  // Dashboard
  dashboard_total_personnel_label: 'Total Personnel',
  dashboard_total_personnel_subtext: 'Active staff',
  dashboard_pending_req_label: 'Pending Requisitions',
  dashboard_pending_req_subtext: 'Awaiting approval',
  dashboard_low_stock_label: 'Low Stock',
  dashboard_low_stock_subtext: 'Below threshold',
  dashboard_out_stock_label: 'Out of Stock',
  dashboard_out_stock_subtext: 'Needs restock',
  dashboard_fix: 'Fix',
  dashboard_requisition_volume: 'Requisition Volume',
  dashboard_requisition_volume_subtext: 'Last 6 months',
  dashboard_this_year: 'This Year',
  dashboard_last_6m: 'Last 6M',
  dashboard_inventory_distribution: 'Inventory Distribution',
  dashboard_inventory_distribution_subtext: 'By material type',
  dashboard_items_label: 'items',
  dashboard_recent_activity: 'Recent Activity',
  dashboard_table_req_id: 'Req ID',
  dashboard_table_requester: 'Requester',
  dashboard_table_item: 'Item',
  dashboard_table_date: 'Date',

  // Personnel
  personnel_add_button: 'Add Personnel',
  personnel_directory_title: 'Personnel Directory',
  personnel_directory_subtitle: 'Manage and track personnel records.',
  personnel_stat_total: 'Total Personnel',
  personnel_stat_active_now: 'Active Now',
  personnel_stat_on_leave: 'On Leave',
  personnel_search_placeholder: 'Search personnel...',
  personnel_department: 'Department',
  personnel_table_employee: 'Employee',
  personnel_table_contact: 'Contact',
  personnel_table_position: 'Position',
  personnel_back: 'Back to Personnel',
  personnel_create_title: 'Create Personnel',
  personnel_create_subtitle: 'Add a new personnel record.',
  personnel_edit_title: 'Edit Personnel',
  personnel_edit_subtitle: 'Update personnel information.',
  personnel_save_button: 'Create Personnel',
  personnel_delete_button: 'Delete Personnel',
  personnel_delete_confirm_title: 'Delete Personnel?',
  personnel_delete_confirm_body: 'This action cannot be undone.',
  personnel_error_create: 'Failed to create personnel.',
  personnel_error_delete: 'Failed to delete personnel.',
  personnel_error_fetch: 'Failed to fetch personnel.',
  personnel_error_missing_id: 'Missing personnel ID.',
  personnel_error_update: 'Failed to update personnel.',

  // Profile
  profile_title: 'User Profile',
  profile_my_profile: 'My Profile',
  profile_personal_info: 'Personal Information',
  profile_change_photo: 'Change Photo',
  profile_contact_admin_email: 'Contact admin to change email address.',
  profile_security: 'Security',
  profile_change_password: 'Change Password',
  profile_2fa_status: '2FA Status',
  profile_2fa_enabled: 'ENABLED',
  profile_error_fetch: 'Failed to load profile.',
  profile_error_update: 'Failed to update profile.',
  profile_update_success: 'Profile updated successfully.',
  profile_photo_title: 'Profile Photo',
  profile_photo_subtitle_user: 'Upload a profile photo for the user.',
  profile_photo_subtitle_personnel: 'Upload a profile photo for the personnel.',
  profile_photo_subtitle_personnel_update: 'Update the personnel photo.',

  // Sections
  section_personal_information: 'Personal Information',
  section_role_access: 'Role & Access',
  section_role_responsibilities: 'Role Responsibilities',

  // Users
  users_management: 'Users Management',
  users_add_button: 'Add User',
  users_title: 'Users',
  users_subtitle: 'Manage user accounts, roles, and access.',
  users_stat_total: 'Total Users',
  users_stat_active: 'Active',
  users_stat_admins: 'Admins',
  users_stat_inactive: 'Inactive',
  users_search_placeholder: 'Search users...',
  users_all_roles: 'All Roles',
  users_table_user: 'User',
  users_table_last_active: 'Last Active',
  users_no_username: 'No username',
  users_not_found: 'User not found.',
  users_back: 'Back to Users',
  users_create_title: 'Create User',
  users_create_subtitle: 'Add a new user account.',
  users_create_button: 'Create User',
  users_edit_title: 'Edit User',
  users_edit_subtitle: 'Update user account details.',
  users_credentials: 'Credentials',
  users_contact_information: 'Contact Information',
  users_role_status: 'Role & Status',
  users_activity: 'Activity',
  users_created_by: 'Created By',
  users_view_user: 'View User',
  users_password_placeholder: 'Leave blank to keep current password',
  users_suspend_button: 'Suspend User',
  users_suspend_confirm_title: 'Suspend User?',
  users_suspend_confirm_body: 'The user will not be able to sign in until reactivated.',
  users_confirm_suspend: 'Confirm Suspend',
  users_suspending: 'Suspending...',
  users_error_create: 'Failed to create user.',
  users_error_fetch: 'Failed to fetch users.',
  users_error_missing_id: 'Missing user ID.',
  users_error_suspend: 'Failed to suspend user.',
  users_error_update: 'Failed to update user.',
  users_roles: 'Users & Roles',
  users_role_superadmin: 'Super Admin',
  users_role_admin_user: 'Admin User',

  // Workplaces
  workplaces_title: 'Workplaces',
  workplaces_subtitle: 'Manage building and room locations.',
  workplace_add_button: 'Add Workplace',
  workplace_update_button: 'Update Workplace',
  workplace_add_title: 'Add Workplace',
  workplace_building: 'Building',
  workplace_room: 'Room',
  workplace_building_placeholder: 'Building',
  workplace_room_placeholder: 'Room',
  workplace_building_required: 'Building (required)',
  workplace_room_optional: 'Room (optional)',
  workplace_confirm_delete: 'Delete this workplace?',
  workplace_empty: 'No workplaces found.',
  workplace_error_building_required: 'Please enter a building name.',
  workplace_error_duplicate: 'This workplace already exists.',
  workplace_error_duplicate_selected: 'Workplace already exists. Selected the existing entry.',
  workplace_error_fetch: 'Failed to fetch workplaces.',
  workplace_error_load: 'Failed to load workplaces.',
  workplace_error_save: 'Failed to save workplace.',
  workplace_error_create: 'Failed to create workplace.',
  workplace_error_delete: 'Failed to delete workplace.',
  workplace_loading: 'Loading workplaces...',
  workplace_select_optional: 'Select workplace (optional)',

  // Material types
  material_type: 'Material Type',
  material_types_title: 'Material Types',
  material_types_subtitle: 'Manage material categories.',
  material_types_add: 'Add Type',
  material_types_add_title: 'Add Material Type',
  material_types_create_button: 'Create Type',
  material_types_update: 'Update Type',
  material_types_table_title: 'Type Name',
  material_types_label_name: 'Type Name',
  material_types_placeholder: 'Type name',
  material_types_select: 'Select material type',
  material_types_empty: 'No material types found.',
  material_types_error_fetch: 'Failed to fetch material types.',
  material_types_error_create: 'Failed to create material type.',
  material_types_error_delete: 'Failed to delete material type.',
  material_types_error_required: 'Please enter a type name.',
  material_types_error_save: 'Failed to save material type.',
  material_types_confirm_delete: 'Delete this material type?',

  // Materials
  materials_add_button: 'Add Material',
  materials_add_qty: 'Add Quantity',
  materials_add_qty_subtitle: 'Increase available stock for this material.',
  materials_add_qty_title: 'Add Quantity',
  materials_add_value: 'Add Qty',
  materials_all_types: 'All Types',
  materials_all_units: 'All Units',
  materials_back: 'Back to Materials',
  materials_create_subtitle: 'Add a new material to inventory.',
  materials_create_title: 'Create Material',
  materials_delete_button: 'Delete Material',
  materials_delete_confirm_body: 'This action cannot be undone.',
  materials_delete_confirm_title: 'Delete Material?',
  materials_details_title: 'Material Details',
  materials_directory_subtitle: 'Manage and track inventory materials.',
  materials_directory_title: 'Materials Directory',
  materials_edit_subtitle: 'Update material information.',
  materials_edit_title: 'Edit Material',
  materials_empty: 'No materials found.',
  materials_error_add_qty: 'Failed to add quantity.',
  materials_error_create: 'Failed to create material.',
  materials_error_delete: 'Failed to delete material.',
  materials_error_fetch: 'Failed to fetch materials.',
  materials_error_invalid_add_qty: 'Please enter a valid quantity.',
  materials_error_load_details: 'Failed to load material details.',
  materials_error_load_latest: 'Failed to load latest stock.',
  materials_error_missing_id: 'Missing material ID.',
  materials_error_not_found: 'Material not found.',
  materials_error_update: 'Failed to update material.',
  materials_filters_title: 'Filters',
  materials_item_name: 'Material',
  materials_label_current_qty: 'Current Quantity',
  materials_label_initial_qty: 'Initial Quantity',
  materials_label_min_threshold: 'Minimum Threshold',
  materials_label_name: 'Material Name',
  materials_label_unit: 'Unit',
  materials_last_value: 'Current Qty',
  materials_max_qty: 'Max Qty',
  materials_min_qty: 'Min Qty',
  materials_new_value: 'New Qty',
  materials_placeholder_name: 'e.g. Steel Pipe',
  materials_placeholder_unit: 'e.g. pcs, kg',
  materials_qty: 'Qty',
  materials_save_button: 'Create Material',
  materials_search_placeholder: 'Search materials...',
  materials_stat_total_skus: 'Total SKUs',
  materials_stock_status: 'Stock Status',
  materials_table_category: 'Category',
  materials_table_material: 'Material',
  materials_table_quantity: 'Quantity',
  materials_table_unit: 'Unit',
  materials_unit: 'Unit',

  // Requisitions
  requisitions_action_hint: 'Approve or reject this requisition.',
  requisitions_add_item: 'Add Item',
  requisitions_all_materials_added: 'All materials added',
  requisitions_authorizer: 'Authorizer',
  requisitions_back: 'Back to Requisitions',
  requisitions_create_title: 'Create Requisition',
  requisitions_created: 'Created',
  requisitions_creator: 'Requester',
  requisitions_delete_button: 'Delete Requisition',
  requisitions_delete_confirm_body: 'This action cannot be undone.',
  requisitions_delete_confirm_title: 'Delete Requisition?',
  requisitions_details_title: 'Requisition Details',
  requisitions_edit_label: 'Edit',
  requisitions_edit_title: 'Edit Requisition',
  requisitions_empty: 'No requisitions found.',
  requisitions_error_all_materials_selected: 'All materials have been selected.',
  requisitions_error_create: 'Failed to create requisition.',
  requisitions_error_date_future: 'Date cannot be in the future.',
  requisitions_error_delete: 'Failed to delete requisition.',
  requisitions_error_duplicate_material: 'This material is already selected.',
  requisitions_error_evaluate: 'Failed to evaluate requisition.',
  requisitions_error_exceed_stock: 'Quantity exceeds stock',
  requisitions_error_exceed_stock_available: 'Quantity exceeds available stock.',
  requisitions_error_fetch: 'Failed to fetch requisitions.',
  requisitions_error_item_invalid: 'Please complete item details.',
  requisitions_error_item_invalid_edit: 'Please review item details.',
  requisitions_error_item_required: 'Please add at least one item.',
  requisitions_error_login_required: 'Please sign in to approve or reject this requisition.',
  requisitions_error_missing_id: 'Missing requisition ID.',
  requisitions_error_owner_required: 'Please select an owner.',
  requisitions_error_owner_required_edit: 'Please select an owner.',
  requisitions_error_restore_duplicate: 'This material is already in the list.',
  requisitions_error_update: 'Failed to update requisition.',
  requisitions_filter_all_requesters: 'All Requesters',
  requisitions_filter_authorizer: 'Authorizer',
  requisitions_filter_from_date: 'From Date',
  requisitions_filter_requester: 'Requester',
  requisitions_filter_to_date: 'To Date',
  requisitions_filters_title: 'Filters',
  requisitions_label_date_required: 'Required Date',
  requisitions_label_description: 'Description',
  requisitions_label_owner: 'Owner',
  requisitions_label_purpose: 'Purpose',
  requisitions_label_subject: 'Subject',
  requisitions_login_required: 'Please',
  requisitions_login_required_suffix: 'to approve or reject this requisition.',
  requisitions_mark_for_delete: 'Mark for delete',
  requisitions_marked_for_delete: 'Marked for delete',
  requisitions_material_details: 'Material Details',
  requisitions_pending_authorization: 'Pending Authorization',
  requisitions_placeholder_description: 'Describe the request',
  requisitions_placeholder_purpose: 'Purpose of request',
  requisitions_placeholder_subject: 'Requisition subject',
  requisitions_reference_no: 'Reference No',
  requisitions_remaining: 'Remaining',
  requisitions_restore_item: 'Restore item',
  requisitions_search_placeholder: 'Search requisitions...',
  requisitions_slip: 'Slip',
  requisitions_submit: 'Submit Requisition',
  requisitions_submitting: 'Submitting...',
  requisitions_table_authorizer: 'Authorizer',
  requisitions_table_date_created: 'Date Created',
  requisitions_table_items: 'Items',
  requisitions_table_ref_no: 'Ref No',
  requisitions_table_requester: 'Requester',
  requisitions_table_subject: 'Subject',
  requisitions_timeline: 'Timeline',
  requisitions_title: 'Requisitions',
  requisitions_unassigned: 'Unassigned',
  requisitions_view_label: 'View',

  // Material search
  material_already_selected: 'Already selected',
  material_clear_selected: 'Clear selected material',
  material_no_results: 'No material found',
  material_search_placeholder: 'Search materials...',
  material_stock: 'Stock',

  // User search
  user_clear_selected: 'Clear selected user',
  user_no_results: 'No user found',
  user_search_placeholder: 'Search users...',

  // Not found page
  not_found_back_dashboard: 'Return to Dashboard',
  not_found_description: 'We could not locate the personnel record or material requisition you are looking for. It may have been moved, deleted, or the ID is incorrect.',
  not_found_page_error: 'Page Error',
  not_found_reference: 'Reference:',
  not_found_report_issue: 'Report Issue',
  not_found_subtitle: 'The resource you requested is unavailable.',
  not_found_title: '404 Not Found',
} as const;
const thTranslations: typeof enTranslations = {
  // Navigation & labels
  dashboard: 'แดชบอร์ด',
  personnel: 'บุคลากร',
  inventory: 'คลังวัสดุ',
  requisitions: 'ใบขอวัสดุ',
  users_roles: 'ผู้ใช้และสิทธิ์',
  settings: 'ตั้งค่า',
  storage_usage: 'การใช้พื้นที่',
  new_requisition: 'สร้างใบขอวัสดุ',
  logout: 'ออกจากระบบ',
  search_placeholder: 'ค้นหา...',
  admin_portal: 'พอร์ทัลผู้ดูแล',
  admin_user: 'ผู้ดูแลระบบ',
  language: 'ภาษา',
  eng: 'อังกฤษ',
  thai: 'ไทย',
  home: 'หน้าหลัก',
  users: 'ผู้ใช้',
  workplaces: 'สถานที่ทำงาน',
  create: 'สร้าง',
  edit: 'แก้ไข',
  view: 'ดู',
  slip: 'สลิป',
  material_types: 'ประเภทวัสดุ',
  workplace: 'สถานที่ทำงาน',
  system: 'ระบบ',
  user: 'ผู้ใช้',

  // Roles, access, status
  role_admin: 'ผู้ดูแล',
  role_user: 'ผู้ใช้',
  role_personnel: 'บุคลากร',
  role_unknown: 'ไม่ทราบ',
  access_full: 'สิทธิ์เต็มรูปแบบ',
  access_standard: 'สิทธิ์มาตรฐาน',
  access_na: 'ไม่ระบุ',
  status_active: 'ใช้งานอยู่',
  status_inactive: 'ไม่ใช้งาน',
  status_suspended: 'ถูกระงับ',
  status_unknown: 'ไม่ทราบ',
  status_approved: 'อนุมัติ',
  status_pending: 'รออนุมัติ',
  status_rejected: 'ไม่อนุมัติ',
  stock_in: 'มีสินค้า',
  stock_low: 'ใกล้หมด',
  stock_out: 'สินค้าหมด',

  // Common
  common_actions: 'การดำเนินการ',
  common_all: 'ทั้งหมด',
  common_all_status: 'ทุกสถานะ',
  common_apply_filters: 'ใช้ตัวกรอง',
  common_assigned: 'มอบหมายแล้ว',
  common_cancel: 'ยกเลิก',
  common_choose_file: 'เลือกไฟล์',
  common_clear: 'ล้าง',
  common_close: 'ปิด',
  common_confirm_delete: 'ยืนยันการลบ',
  common_date_created: 'วันที่สร้าง',
  common_delete: 'ลบ',
  common_deleting: 'กำลังลบ...',
  common_edit: 'แก้ไข',
  common_error: 'ข้อผิดพลาด',
  common_error_required_fields: 'กรุณากรอกข้อมูลที่จำเป็นให้ครบ',
  common_filters: 'ตัวกรอง',
  common_from_date: 'จากวันที่',
  common_items: 'รายการ',
  common_last_updated: 'อัปเดตล่าสุด',
  common_next: 'ถัดไป',
  common_no_changes: 'ไม่มีการเปลี่ยนแปลง',
  common_of: 'จาก',
  common_optional: 'ไม่บังคับ',
  common_previous: 'ก่อนหน้า',
  common_remove: 'ลบออก',
  common_required_hint: 'ช่องที่จำเป็นต้องกรอก',
  common_reset: 'รีเซ็ต',
  common_results: 'ผลลัพธ์',
  common_save_changes: 'บันทึกการเปลี่ยนแปลง',
  common_saving: 'กำลังบันทึก...',
  common_showing: 'แสดง',
  common_status: 'สถานะ',
  common_to: 'ถึง',
  common_to_date: 'ถึงวันที่',
  common_unassigned: 'ยังไม่มอบหมาย',
  common_updated: 'อัปเดต',
  common_updating: 'กำลังอัปเดต...',
  common_view_all: 'ดูทั้งหมด',

  // Fallbacks
  no_email: 'ไม่มีอีเมล',
  no_workplace: 'ไม่มีสถานที่ทำงาน',
  not_available: 'ไม่ระบุ',
  not_set: 'ยังไม่ตั้งค่า',

  // Labels & placeholders
  label_display_name: 'ชื่อที่แสดง',
  label_email_address: 'อีเมล',
  label_full_name: 'ชื่อ-นามสกุล',
  label_password: 'รหัสผ่าน',
  label_position: 'ตำแหน่ง',
  label_position_title: 'ตำแหน่งงาน',
  label_role: 'บทบาท',
  label_username: 'ชื่อผู้ใช้',
  placeholder_display_name_example: 'เช่น สมชาย ใจดี',
  placeholder_email_example: 'เช่น name@company.com',
  placeholder_fullname_example: 'เช่น สมชาย ใจดี',
  placeholder_position_example: 'เช่น ผู้จัดการคลังสินค้า',
  placeholder_username_example: 'เช่น jdoe',

  // Date picker
  datepicker_no_date_selected: 'ยังไม่ได้เลือกวันที่',
  datepicker_invalid_date: 'วันที่ไม่ถูกต้อง',
  datepicker_today: 'วันนี้',

  // Login
  login_hero_title: 'ระบบจัดการ',
  login_hero_highlight: 'ภายในองค์กร',
  login_hero_subtitle: 'จัดการใบขอวัสดุ คลังสินค้า และบุคลากรได้ในที่เดียว',
  login_title: 'เข้าสู่ระบบ',
  login_subtitle: 'กรอกข้อมูลเพื่อเข้าสู่ระบบ',
  login_email_placeholder: 'อีเมล',
  login_password_placeholder: 'รหัสผ่าน',
  login_forgot_password: 'ลืมรหัสผ่าน?',
  login_sign_in: 'เข้าสู่ระบบ',
  login_logging_in: 'กำลังเข้าสู่ระบบ...',
  login_footer: '© ระบบจัดการภายในองค์กร',

  // Dashboard
  dashboard_total_personnel_label: 'บุคลากรทั้งหมด',
  dashboard_total_personnel_subtext: 'บุคลากรที่ใช้งานอยู่',
  dashboard_pending_req_label: 'ใบขอวัสดุที่รออนุมัติ',
  dashboard_pending_req_subtext: 'รอการอนุมัติ',
  dashboard_low_stock_label: 'สต็อกใกล้หมด',
  dashboard_low_stock_subtext: 'ต่ำกว่าค่าขั้นต่ำ',
  dashboard_out_stock_label: 'สต็อกหมด',
  dashboard_out_stock_subtext: 'ต้องเติมสต็อก',
  dashboard_fix: 'แก้ไข',
  dashboard_requisition_volume: 'ปริมาณใบขอวัสดุ',
  dashboard_requisition_volume_subtext: 'ย้อนหลัง 6 เดือน',
  dashboard_this_year: 'ปีนี้',
  dashboard_last_6m: '6 เดือนล่าสุด',
  dashboard_inventory_distribution: 'สัดส่วนคลังวัสดุ',
  dashboard_inventory_distribution_subtext: 'ตามประเภทวัสดุ',
  dashboard_items_label: 'รายการ',
  dashboard_recent_activity: 'กิจกรรมล่าสุด',
  dashboard_table_req_id: 'เลขที่ใบขอ',
  dashboard_table_requester: 'ผู้ขอ',
  dashboard_table_item: 'รายการ',
  dashboard_table_date: 'วันที่',

  // Personnel
  personnel_add_button: 'เพิ่มบุคลากร',
  personnel_directory_title: 'รายชื่อบุคลากร',
  personnel_directory_subtitle: 'จัดการและติดตามข้อมูลบุคลากร',
  personnel_stat_total: 'บุคลากรทั้งหมด',
  personnel_stat_active_now: 'กำลังปฏิบัติงาน',
  personnel_stat_on_leave: 'ลางาน',
  personnel_search_placeholder: 'ค้นหาบุคลากร...',
  personnel_department: 'แผนก',
  personnel_table_employee: 'พนักงาน',
  personnel_table_contact: 'ติดต่อ',
  personnel_table_position: 'ตำแหน่ง',
  personnel_back: 'กลับไปหน้าบุคลากร',
  personnel_create_title: 'สร้างข้อมูลบุคลากร',
  personnel_create_subtitle: 'เพิ่มข้อมูลบุคลากรใหม่',
  personnel_edit_title: 'แก้ไขข้อมูลบุคลากร',
  personnel_edit_subtitle: 'อัปเดตข้อมูลบุคลากร',
  personnel_save_button: 'สร้างบุคลากร',
  personnel_delete_button: 'ลบบุคลากร',
  personnel_delete_confirm_title: 'ลบบุคลากรนี้?',
  personnel_delete_confirm_body: 'การดำเนินการนี้ไม่สามารถย้อนกลับได้',
  personnel_error_create: 'สร้างบุคลากรไม่สำเร็จ',
  personnel_error_delete: 'ลบบุคลากรไม่สำเร็จ',
  personnel_error_fetch: 'โหลดข้อมูลบุคลากรไม่สำเร็จ',
  personnel_error_missing_id: 'ไม่พบรหัสบุคลากร',
  personnel_error_update: 'อัปเดตบุคลากรไม่สำเร็จ',

  // Profile
  profile_title: 'โปรไฟล์ผู้ใช้',
  profile_my_profile: 'โปรไฟล์ของฉัน',
  profile_personal_info: 'ข้อมูลส่วนตัว',
  profile_change_photo: 'เปลี่ยนรูปภาพ',
  profile_contact_admin_email: 'ติดต่อผู้ดูแลเพื่อเปลี่ยนอีเมล',
  profile_security: 'ความปลอดภัย',
  profile_change_password: 'เปลี่ยนรหัสผ่าน',
  profile_2fa_status: 'สถานะ 2FA',
  profile_2fa_enabled: 'เปิดใช้งาน',
  profile_error_fetch: 'โหลดโปรไฟล์ไม่สำเร็จ',
  profile_error_update: 'อัปเดตโปรไฟล์ไม่สำเร็จ',
  profile_update_success: 'อัปเดตโปรไฟล์เรียบร้อยแล้ว',
  profile_photo_title: 'รูปโปรไฟล์',
  profile_photo_subtitle_user: 'อัปโหลดรูปโปรไฟล์สำหรับผู้ใช้',
  profile_photo_subtitle_personnel: 'อัปโหลดรูปโปรไฟล์สำหรับบุคลากร',
  profile_photo_subtitle_personnel_update: 'อัปเดตรูปโปรไฟล์บุคลากร',

  // Sections
  section_personal_information: 'ข้อมูลส่วนตัว',
  section_role_access: 'บทบาทและสิทธิ์',
  section_role_responsibilities: 'หน้าที่ตามบทบาท',

  // Users
  users_management: 'การจัดการผู้ใช้',
  users_add_button: 'เพิ่มผู้ใช้',
  users_title: 'ผู้ใช้',
  users_subtitle: 'จัดการบัญชีผู้ใช้ บทบาท และสิทธิ์การเข้าถึง',
  users_stat_total: 'ผู้ใช้ทั้งหมด',
  users_stat_active: 'ใช้งานอยู่',
  users_stat_admins: 'ผู้ดูแล',
  users_stat_inactive: 'ไม่ใช้งาน',
  users_search_placeholder: 'ค้นหาผู้ใช้...',
  users_all_roles: 'ทุกบทบาท',
  users_table_user: 'ผู้ใช้',
  users_table_last_active: 'ใช้งานล่าสุด',
  users_no_username: 'ไม่มีชื่อผู้ใช้',
  users_not_found: 'ไม่พบผู้ใช้',
  users_back: 'กลับไปหน้าผู้ใช้',
  users_create_title: 'สร้างผู้ใช้',
  users_create_subtitle: 'เพิ่มบัญชีผู้ใช้ใหม่',
  users_create_button: 'สร้างผู้ใช้',
  users_edit_title: 'แก้ไขผู้ใช้',
  users_edit_subtitle: 'อัปเดตข้อมูลผู้ใช้',
  users_credentials: 'ข้อมูลเข้าสู่ระบบ',
  users_contact_information: 'ข้อมูลติดต่อ',
  users_role_status: 'บทบาทและสถานะ',
  users_activity: 'กิจกรรม',
  users_created_by: 'สร้างโดย',
  users_view_user: 'ดูผู้ใช้',
  users_password_placeholder: 'เว้นว่างเพื่อคงรหัสผ่านเดิม',
  users_suspend_button: 'ระงับผู้ใช้',
  users_suspend_confirm_title: 'ระงับผู้ใช้นี้?',
  users_suspend_confirm_body: 'ผู้ใช้จะไม่สามารถเข้าสู่ระบบได้จนกว่าจะเปิดใช้งานอีกครั้ง',
  users_confirm_suspend: 'ยืนยันการระงับ',
  users_suspending: 'กำลังระงับ...',
  users_error_create: 'สร้างผู้ใช้ไม่สำเร็จ',
  users_error_fetch: 'โหลดผู้ใช้ไม่สำเร็จ',
  users_error_missing_id: 'ไม่พบรหัสผู้ใช้',
  users_error_suspend: 'ระงับผู้ใช้ไม่สำเร็จ',
  users_error_update: 'อัปเดตผู้ใช้ไม่สำเร็จ',
  users_roles: 'ผู้ใช้และสิทธิ์',
  users_role_superadmin: 'ผู้ดูแลขั้นสูง',
  users_role_admin_user: 'ผู้ดูแลระบบ',

  // Workplaces
  workplaces_title: 'สถานที่ทำงาน',
  workplaces_subtitle: 'จัดการอาคารและห้อง',
  workplace_add_button: 'เพิ่มสถานที่ทำงาน',
  workplace_update_button: 'อัปเดตสถานที่ทำงาน',
  workplace_add_title: 'เพิ่มสถานที่ทำงาน',
  workplace_building: 'อาคาร',
  workplace_room: 'ห้อง',
  workplace_building_placeholder: 'อาคาร',
  workplace_room_placeholder: 'ห้อง',
  workplace_building_required: 'อาคาร (จำเป็น)',
  workplace_room_optional: 'ห้อง (ไม่บังคับ)',
  workplace_confirm_delete: 'ลบสถานที่ทำงานนี้?',
  workplace_empty: 'ไม่พบสถานที่ทำงาน',
  workplace_error_building_required: 'กรุณาระบุชื่ออาคาร',
  workplace_error_duplicate: 'มีสถานที่ทำงานนี้อยู่แล้ว',
  workplace_error_duplicate_selected: 'มีสถานที่ทำงานนี้อยู่แล้วและได้เลือกให้แล้ว',
  workplace_error_fetch: 'โหลดสถานที่ทำงานไม่สำเร็จ',
  workplace_error_load: 'โหลดสถานที่ทำงานไม่สำเร็จ',
  workplace_error_save: 'บันทึกสถานที่ทำงานไม่สำเร็จ',
  workplace_error_create: 'สร้างสถานที่ทำงานไม่สำเร็จ',
  workplace_error_delete: 'ลบสถานที่ทำงานไม่สำเร็จ',
  workplace_loading: 'กำลังโหลดสถานที่ทำงาน...',
  workplace_select_optional: 'เลือกสถานที่ทำงาน (ไม่บังคับ)',

  // Material types
  material_type: 'ประเภทวัสดุ',
  material_types_title: 'ประเภทวัสดุ',
  material_types_subtitle: 'จัดการหมวดหมู่วัสดุ',
  material_types_add: 'เพิ่มประเภท',
  material_types_add_title: 'เพิ่มประเภทวัสดุ',
  material_types_create_button: 'สร้างประเภท',
  material_types_update: 'อัปเดตประเภท',
  material_types_table_title: 'ชื่อประเภท',
  material_types_label_name: 'ชื่อประเภท',
  material_types_placeholder: 'ชื่อประเภท',
  material_types_select: 'เลือกประเภทวัสดุ',
  material_types_empty: 'ไม่พบประเภทวัสดุ',
  material_types_error_fetch: 'โหลดประเภทวัสดุไม่สำเร็จ',
  material_types_error_create: 'สร้างประเภทวัสดุไม่สำเร็จ',
  material_types_error_delete: 'ลบประเภทวัสดุไม่สำเร็จ',
  material_types_error_required: 'กรุณากรอกชื่อประเภท',
  material_types_error_save: 'บันทึกประเภทวัสดุไม่สำเร็จ',
  material_types_confirm_delete: 'ลบประเภทวัสดุนี้?',

  // Materials
  materials_add_button: 'เพิ่มวัสดุ',
  materials_add_qty: 'เพิ่มจำนวน',
  materials_add_qty_subtitle: 'เพิ่มจำนวนวัสดุในคลัง',
  materials_add_qty_title: 'เพิ่มจำนวน',
  materials_add_value: 'เพิ่มจำนวน',
  materials_all_types: 'ทุกประเภท',
  materials_all_units: 'ทุกหน่วย',
  materials_back: 'กลับไปหน้าวัสดุ',
  materials_create_subtitle: 'เพิ่มวัสดุใหม่เข้าสู่คลัง',
  materials_create_title: 'สร้างวัสดุ',
  materials_delete_button: 'ลบวัสดุ',
  materials_delete_confirm_body: 'การดำเนินการนี้ไม่สามารถย้อนกลับได้',
  materials_delete_confirm_title: 'ลบวัสดุนี้?',
  materials_details_title: 'รายละเอียดวัสดุ',
  materials_directory_subtitle: 'จัดการและติดตามวัสดุในคลัง',
  materials_directory_title: 'คลังวัสดุ',
  materials_edit_subtitle: 'อัปเดตข้อมูลวัสดุ',
  materials_edit_title: 'แก้ไขวัสดุ',
  materials_empty: 'ไม่พบวัสดุ',
  materials_error_add_qty: 'เพิ่มจำนวนไม่สำเร็จ',
  materials_error_create: 'สร้างวัสดุไม่สำเร็จ',
  materials_error_delete: 'ลบวัสดุไม่สำเร็จ',
  materials_error_fetch: 'โหลดข้อมูลวัสดุไม่สำเร็จ',
  materials_error_invalid_add_qty: 'กรุณากรอกจำนวนที่ถูกต้อง',
  materials_error_load_details: 'โหลดรายละเอียดวัสดุไม่สำเร็จ',
  materials_error_load_latest: 'โหลดสต็อกล่าสุดไม่สำเร็จ',
  materials_error_missing_id: 'ไม่พบรหัสวัสดุ',
  materials_error_not_found: 'ไม่พบวัสดุ',
  materials_error_update: 'อัปเดตวัสดุไม่สำเร็จ',
  materials_filters_title: 'ตัวกรอง',
  materials_item_name: 'วัสดุ',
  materials_label_current_qty: 'จำนวนปัจจุบัน',
  materials_label_initial_qty: 'จำนวนเริ่มต้น',
  materials_label_min_threshold: 'ขั้นต่ำที่ต้องมี',
  materials_label_name: 'ชื่อวัสดุ',
  materials_label_unit: 'หน่วย',
  materials_last_value: 'จำนวนปัจจุบัน',
  materials_max_qty: 'จำนวนสูงสุด',
  materials_min_qty: 'จำนวนต่ำสุด',
  materials_new_value: 'จำนวนใหม่',
  materials_placeholder_name: 'เช่น ท่อเหล็ก',
  materials_placeholder_unit: 'เช่น ชิ้น, กก.',
  materials_qty: 'จำนวน',
  materials_save_button: 'สร้างวัสดุ',
  materials_search_placeholder: 'ค้นหาวัสดุ...',
  materials_stat_total_skus: 'จำนวน SKU ทั้งหมด',
  materials_stock_status: 'สถานะสต็อก',
  materials_table_category: 'ประเภท',
  materials_table_material: 'วัสดุ',
  materials_table_quantity: 'จำนวน',
  materials_table_unit: 'หน่วย',
  materials_unit: 'หน่วย',

  // Requisitions
  requisitions_action_hint: 'อนุมัติหรือปฏิเสธใบขอวัสดุนี้',
  requisitions_add_item: 'เพิ่มรายการ',
  requisitions_all_materials_added: 'เพิ่มวัสดุครบแล้ว',
  requisitions_authorizer: 'ผู้อนุมัติ',
  requisitions_back: 'กลับไปหน้าใบขอวัสดุ',
  requisitions_create_title: 'สร้างใบขอวัสดุ',
  requisitions_created: 'สร้างเมื่อ',
  requisitions_creator: 'ผู้ยื่นคำขอ',
  requisitions_delete_button: 'ลบใบขอวัสดุ',
  requisitions_delete_confirm_body: 'การดำเนินการนี้ไม่สามารถย้อนกลับได้',
  requisitions_delete_confirm_title: 'ลบใบขอวัสดุนี้?',
  requisitions_details_title: 'รายละเอียดใบขอวัสดุ',
  requisitions_edit_label: 'แก้ไข',
  requisitions_edit_title: 'แก้ไขใบขอวัสดุ',
  requisitions_empty: 'ไม่พบใบขอวัสดุ',
  requisitions_error_all_materials_selected: 'เลือกวัสดุครบแล้ว',
  requisitions_error_create: 'สร้างใบขอวัสดุไม่สำเร็จ',
  requisitions_error_date_future: 'วันที่ไม่สามารถเป็นอนาคตได้',
  requisitions_error_delete: 'ลบใบขอวัสดุไม่สำเร็จ',
  requisitions_error_duplicate_material: 'วัสดุนี้ถูกเลือกแล้ว',
  requisitions_error_evaluate: 'ประเมินใบขอวัสดุไม่สำเร็จ',
  requisitions_error_exceed_stock: 'จำนวนเกินสต็อกที่มี',
  requisitions_error_exceed_stock_available: 'จำนวนเกินสต็อกที่มีอยู่',
  requisitions_error_fetch: 'โหลดใบขอวัสดุไม่สำเร็จ',
  requisitions_error_item_invalid: 'กรุณากรอกข้อมูลรายการวัสดุให้ครบ',
  requisitions_error_item_invalid_edit: 'กรุณาตรวจสอบข้อมูลรายการวัสดุให้ครบ',
  requisitions_error_item_required: 'กรุณาเพิ่มรายการวัสดุอย่างน้อยหนึ่งรายการ',
  requisitions_error_login_required: 'โปรดเข้าสู่ระบบเพื่ออนุมัติหรือปฏิเสธใบขอวัสดุ',
  requisitions_error_missing_id: 'ไม่พบรหัสใบขอวัสดุ',
  requisitions_error_owner_required: 'กรุณาเลือกผู้รับผิดชอบ',
  requisitions_error_owner_required_edit: 'กรุณาเลือกผู้รับผิดชอบ',
  requisitions_error_restore_duplicate: 'รายการนี้มีอยู่แล้วในรายการ',
  requisitions_error_update: 'อัปเดตใบขอวัสดุไม่สำเร็จ',
  requisitions_filter_all_requesters: 'ผู้ขอทั้งหมด',
  requisitions_filter_authorizer: 'ผู้อนุมัติ',
  requisitions_filter_from_date: 'จากวันที่',
  requisitions_filter_requester: 'ผู้ขอ',
  requisitions_filter_to_date: 'ถึงวันที่',
  requisitions_filters_title: 'ตัวกรอง',
  requisitions_label_date_required: 'วันที่ต้องการ',
  requisitions_label_description: 'รายละเอียด',
  requisitions_label_owner: 'ผู้รับผิดชอบ',
  requisitions_label_purpose: 'วัตถุประสงค์',
  requisitions_label_subject: 'หัวข้อ',
  requisitions_login_required: 'โปรด',
  requisitions_login_required_suffix: 'เพื่ออนุมัติหรือปฏิเสธใบขอวัสดุนี้',
  requisitions_mark_for_delete: 'ทำเครื่องหมายเพื่อลบ',
  requisitions_marked_for_delete: 'ทำเครื่องหมายเพื่อลบแล้ว',
  requisitions_material_details: 'รายละเอียดวัสดุ',
  requisitions_pending_authorization: 'รอการอนุมัติ',
  requisitions_placeholder_description: 'อธิบายรายละเอียดคำขอ',
  requisitions_placeholder_purpose: 'วัตถุประสงค์ของคำขอ',
  requisitions_placeholder_subject: 'หัวข้อใบขอวัสดุ',
  requisitions_reference_no: 'เลขที่อ้างอิง',
  requisitions_remaining: 'คงเหลือ',
  requisitions_restore_item: 'กู้คืนรายการ',
  requisitions_search_placeholder: 'ค้นหาใบขอวัสดุ...',
  requisitions_slip: 'สลิป',
  requisitions_submit: 'ส่งใบขอวัสดุ',
  requisitions_submitting: 'กำลังส่ง...',
  requisitions_table_authorizer: 'ผู้อนุมัติ',
  requisitions_table_date_created: 'วันที่สร้าง',
  requisitions_table_items: 'รายการ',
  requisitions_table_ref_no: 'เลขที่อ้างอิง',
  requisitions_table_requester: 'ผู้ขอ',
  requisitions_table_subject: 'หัวข้อ',
  requisitions_timeline: 'ไทม์ไลน์',
  requisitions_title: 'ใบขอวัสดุ',
  requisitions_unassigned: 'ยังไม่มอบหมาย',
  requisitions_view_label: 'ดู',

  // Material search
  material_already_selected: 'เลือกแล้ว',
  material_clear_selected: 'ล้างวัสดุที่เลือก',
  material_no_results: 'ไม่พบวัสดุ',
  material_search_placeholder: 'ค้นหาวัสดุ...',
  material_stock: 'สต็อก',

  // User search
  user_clear_selected: 'ล้างผู้ใช้ที่เลือก',
  user_no_results: 'ไม่พบผู้ใช้',
  user_search_placeholder: 'ค้นหาผู้ใช้...',

  // Not found page
  not_found_back_dashboard: 'กลับไปแดชบอร์ด',
  not_found_description: 'ไม่พบข้อมูลบุคลากรหรือใบขอวัสดุที่คุณค้นหา อาจถูกย้าย ลบ หรือรหัสไม่ถูกต้อง',
  not_found_page_error: 'ข้อผิดพลาดของหน้า',
  not_found_reference: 'อ้างอิง:',
  not_found_report_issue: 'รายงานปัญหา',
  not_found_subtitle: 'ไม่พบทรัพยากรที่คุณร้องขอ',
  not_found_title: '404 ไม่พบหน้า',
} as const;

const translations: Record<Language, TranslationMap> = {
  en: enTranslations,
  th: thTranslations,
};

type TranslationKey = keyof typeof enTranslations;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LANGUAGE_STORAGE_KEY = 'app_language';

const resolveInitialLanguage = (): Language => {
  const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return storedLanguage === 'th' ? 'th' : 'en';
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(resolveInitialLanguage);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
  };

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key: TranslationKey) => translations[language][key],
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = (): LanguageContextValue => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
};
